name: test-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install dependencies
      run: sudo apt-get install emacs

    - name: make
      run: make -C src/

    - name: build docs
      run: make -C src/ doc

    - name: GitHub Pages Deploy
      uses: appleboy/gh-pages-action@v0.0.2

    - name: checkout
      uses: actions/checkout@v1

    - name: deploy docs
      uses: ./
      with:
        username: scemama
        password: 7da28e533792db220a4811fc4e487b8ba817862f
        remote_url: https://github.com/appleboy/gh-pages-action.git


  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install emacs
    - name: Checkout submodules using a PAT
      run: |
           git config --file .gitmodules --get-regexp url | while read url; do
             git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ secrets.CI_PAT }}:${{ secrets.CI_PAT }}@github.com\//")
           done
           git submodule sync
           git submodule update --init --recursive
    - name: make
      run: make -C src/ test
