name: test-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  x86_ubuntu:

    runs-on: ubuntu-latest
    name: x86 Ubuntu latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install emacs autoconf libhdf5-dev

    - name: Install trexio
      run: |
        export TAG=v2.0
        export VERSION=2.0.0
        wget https://github.com/TREX-CoE/trexio/releases/download/${TAG}/trexio-${VERSION}.tar.gz
        tar -zxf trexio-${VERSION}.tar.gz
        cd trexio-${VERSION}
        ./configure --prefix=/usr
        make -j 8
        sudo make install

    - name: Build
      run: |
        ./autogen.sh
        ./configure --enable-silent-rules --enable-debug
        make -j 8

    - name: Run test
      run: |
        make -j check

    - name: Archive test log file
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: test-suite.log

    - name: Dist test
      run: |
        make distcheck

    - name: Archive test log file
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: dist-report
        path: test-suite.log


#  x86_macos:
#
#    runs-on: macos-latest
#    name: x86 MacOS latest
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: install dependencies
#      run: |
#        brew install gfortran-10
#        brew install emacs
#        brew install autoconf automake libtool
#    - name: install trexio
#      run: |
#        wget https://github.com/TREX-CoE/trexio/releases/download/v1.0/trexio-1.0.0.tar.gz
#        tar -zxf trexio-1.0.0.tar.gz
#        cd trexio-1.0.0
#        ./configure
#        make -j 8
#        sudo make install
#    - name: Run test
#      run: |
#        ./autogen.sh
#        ./configure --enable-silent-rules --enable-debug
#        make -j 8
#        make -j check
#        make distcheck
