name: test-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install emacs autoconf
    - name: autoreconf
      run: autoreconf -i
    - name: ./configure
      run: QMCKL_DEVEL=1 ./configure --enable-silent-rules --enable-maintainer-mode --enable-debug
    - name: make
      run: make -j 8
    - name: make check
      run: make -j check
    - name: make distcheck
      run: make distcheck
