name: test-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install emacs autoconf
    - name: Checkout submodules using a PAT
      run: |
           git config --file .gitmodules --get-regexp url | while read url; do
             git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ secrets.CI_PAT }}:${{ secrets.CI_PAT }}@github.com\//")
           done
           git submodule sync
           git submodule update --init --recursive
    - name: ./autogen.sh
      run: ./autogen.sh
    - name: ./configure
      run: ./configure --with-debug
    - name: make
      run: make -C src/ check
    - name: make
      run: make distcheck
