name: test-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  x86_ubuntu:

    runs-on: ubuntu-latest
    name: x86 Ubuntu latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install emacs autoconf
    - name: Run test
      run: |
        ./autogen.sh
        QMCKL_DEVEL=1 ./configure --enable-silent-rules --enable-maintainer-mode --enable-debug
        make -j 8
        make -j check
        make distcheck
    - name: Archive test log file
      uses: actions/upload-artifact@v2
      with:
        name: test-suite.log
        path: test-suite.log

#  x86_macos:
#
#    runs-on: macos-latest
#    name: x86 MacOS latest
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: install dependencies
#      run: |
#        brew install gfortran-10
#        brew install emacs
#        brew install autoconf automake libtool
#    - name: Run test
#      run: |
#        ./autogen.sh
#        QMCKL_DEVEL=1 ./configure --enable-silent-rules --enable-maintainer-mode --enable-debug
#        make -j 8
#        make -j check
#        make distcheck
